export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_ERROR = "GET_ALL_USERS_ERROR";

export const GET_POST_ACTIVITY_REQUEST = "GET_POST_ACTIVITY_REQUEST";
export const GET_POST_ACTIVITY_SUCCESS = "GET_POST_ACTIVITY_SUCCESS";
export const GET_POST_ACTIVITY_ERROR = "GET_POST_ACTIVITY_ERROR";

export const GET_SUGGEST_FRIEND_REQUEST = "GET_SUGGEST_FRIEND_REQUEST";
export const GET_SUGGEST_FRIEND_SUCCESS = "GET_SUGGEST_FRIEND_SUCCESS";
export const GET_SUGGEST_FRIEND_ERROR = "GET_SUGGEST_FRIEND_ERROR";

export const GET_POST_HEARTS_REQUEST = "GET_POST_HEARTS_REQUEST";
export const GET_POST_HEARTS_SUCCESS = "GET_POST_HEARTS_SUCCESS";
export const GET_POST_HEARTS_ERROR = "GET_POST_HEARTS_ERROR";

export const GET_TOGGLE_SETTING = "GET_TOGGLE_SETTING";

export const GET_TOGGLE_ABOUT_ME = "GET_TOGGLE_ABOUT_ME";

export const GET_TOGGLE_BANNED = "GET_TOGGLE_BANNED";

export const GET_DARKMODE = "GET_DARKMODE";

export const GET_LIST_FOLLOWINGS = "GET_LIST_FOLLOWINGS";
export const REMOVE_ITEM_LIST_FOLLOWINGS = "REMOVE_ITEM_LIST_FOLLOWINGS";

export const GET_PARTNER = "GET_PARTNER";

export const GET_PARTNERS_COUNT = "GET_PARTNERS_COUNT";
export const INC_PARTNERS_COUNT = "INC_PARTNERS_COUNT";
export const DEC_PARTNERS_COUNT = "DEC_PARTNERS_COUNT";

export const GET_MESSAGES_COUNT = "GET_MESSAGES_COUNT";
export const INC_MESSAGES_COUNT = "INC_MESSAGES_COUNT";

export const GET_FEED_CATEGORY = "GET_FEED_CATEGORY";

export const GET_USERS_ONLINE = "GET_USERS_ONLINE";

export const SET_POST_COMMENTS = "SET_POST_COMMENTS";
export const INSERT_POST_COMMENTS = "INSERT_POST_COMMENTS";
export const CREATE_POST_COMMENTS = "CREATE_POST_COMMENTS";
export const DELETE_POST_COMMENTS = "DELETE_POST_COMMENTS";

export const GET_LIST_HEARTED_POSTS = "GET_LIST_HEARTED_POSTS";
export const REMOVE_ITEM_LIST_HEARTED_POSTS = "REMOVE_ITEM_LIST_HEARTED_POSTS";

export const GET_LIST_COMMENTS_LOADING = "GET_LIST_COMMENTS_LOADING";
