export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_ERROR = "GET_ALL_USERS_ERROR";

export const GET_POST_ACTIVITY_REQUEST = "GET_POST_ACTIVITY_REQUEST";
export const GET_POST_ACTIVITY_SUCCESS = "GET_POST_ACTIVITY_SUCCESS";
export const GET_POST_ACTIVITY_ERROR = "GET_POST_ACTIVITY_ERROR";

export const GET_POST_HEARTS_REQUEST = "GET_POST_HEARTS_REQUEST";
export const GET_POST_HEARTS_SUCCESS = "GET_POST_HEARTS_SUCCESS";
export const GET_POST_HEARTS_ERROR = "GET_POST_HEARTS_ERROR";

export const GET_TOGGLE_SETTING = "GET_TOGGLE_SETTING";

export const GET_TOGGLE_ABOUT_ME = "GET_TOGGLE_ABOUT_ME";

export const GET_TOGGLE_BANNED = "GET_TOGGLE_BANNED";

export const GET_DARKMODE = "GET_DARKMODE";

export const GET_LIST_FOLLOWINGS = "GET_LIST_FOLLOWINGS";
